name: ci

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout koog-models
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: siarhei-luskanau/koog-models
          path: koog-models

      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Build and publish koog-models
        run: ./gradlew -p koog-models publishToMavenLocal --stacktrace

      # - run: ./gradlew ciJobsMatrixSetup --stacktrace

      - id: set_matrix
        run: echo "matrix=$(jq -c . < ./matrix.json)" >> $GITHUB_OUTPUT



  Koog:
    needs: prepare_matrix
    runs-on: ${{ matrix.variants.runs-on }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare_matrix.outputs.matrix) }}
    name: ${{ matrix.variants.artifact-name }} ${{ matrix.variants.ollama-model-id }} ${{ matrix.variants.runs-on }}
    steps:

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout koog-models
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: siarhei-luskanau/koog-models
          path: koog-models

      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Build and publish koog-models
        run: ./gradlew -p koog-models publishToMavenLocal --stacktrace

      - run: ./gradlew clean :ollama:test -Dollama-model-id=${{ matrix.variants.ollama-model-id }} --tests "${{ matrix.variants.test-group }}" --stacktrace
        if: ${{ matrix.variants.enabled }}

      - name: Sanitize ollama-model-id
        if: always()
        run: echo "SANITIZED_OLLAMA_MODEL_ID=$(echo '${{ matrix.variants.ollama-model-id }}' | tr ',:/' '-')" >> $GITHUB_ENV

      - name: Collect reports
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: reports-${{ env.SANITIZED_OLLAMA_MODEL_ID }}-${{ matrix.variants.artifact-name }}-${{ matrix.variants.runs-on }}
          path: |
            **/build/reports/
          retention-days: 7
